## Digital Footprint

Digital footprints are defined as a way to map and record the online activities of an individual’s life, using trails of metadata to log information that can prove someone’s personal identity [^blue]. These patterns are categorized in two distinct classifications; passive and active digital footprints [^arakerimath]. Passive digital footprints are collected online without direct user intervention, usually in the form of geo-tracking, browsing history, IP addresses and cookies, while active digital footprints are tracked using the deliberate data left by users on social media platforms and other uploading websites [^kaku]. 

Something as innocuous as liking a friend’s photo, commenting or using hashtags creates a digital lineage of personal actions that tracks your daily activity [^arakerimath]. Companies use this data and valuable information to promote specific products to users, targeting individual’s personality traits, behaviours and desires [^arakerimath]. These predictions are implemented with the use of algorithms that search for both passive and active footprints, scraping the web for details such as your name, age, gender, location, and profession [^arakerimath]. 

For these reasons, it is imperative to monitor your personal online activities so as to reduce the possibility of identity theft, and remain vigilant about online scams. The Canadian Centre for Cyber Security provides some important advice which may help individuals in these situations, including installing ad-blockers, firewalls and anti-virus software, implementing multi-factor authentication (MFA), using strong passwords, avoiding public wifi, using virtual private networks (VPN), removing metadata from photos, and more [^canadian]. 

Digital artifacts can be complicated to deal with on a personal level, as seen with people in the midst of transitioning between genders. An empirical analysis was conducted to track the challenges associated with this issue, demonstrating that this process was problematic for most. This resulted in either editing personal data on Facebook manually to keep their previous contacts, by maintaining multiple accounts with different names, or by creating an entirely new account [^haimson]. This fact raises concerns about how digital footprints can impact our lives in intricate ways, especially for those wanting to edit or erase digital artifacts from the web. As designers, we must consider these issues when creating apps and websites, implementing ways to easily delete or forget information in conjunction with remembering [^haimson]. This data contains a multitude of details which may alter your daily life in various ways, so it is essential to understand the implications of digital footprints and the secure solutions, protecting your IRL identity while maintaining your online privacy.

[^arakerimath]: Arakerimath, Anjana R., & Gupta, Pramod Kumar. "Digital Footprint: Pros, Cons, and Future." *International Journal of Latest Technology in Engineering, Management & Applied Science* 4, no. 10 (2015): 52–56. https://www.ijltemas.in/DigitalLibrary/Vol.4Issue10/52-56.pdf. 

[^blue]: Blue, Juanita, Condell, Joan, & Lunney, Tom. "Digital Footprints: Your Unique Identity." ResearchGate, 2018. https://www.researchgate.net/publication/328896992_Digital_Footprints_Your_Unique_Identity. 

[^canadian]: Canadian Centre for Cyber Security. "Digital Footprint." ITSAP.00.133. https://www.cyber.gc.ca/sites/default/files/itsap.00.133-digital-footprint.pdf. 

[^haimson]: Haimson, Oliver L., Brubaker, Jed R., Dombrowski, Lynn, & Hayes, Gillian R.. "Digital Footprints and Changing Networks During Online Identity Transitions." https://oliverhaimson.com/PDFs/HaimsonDigitalFootprints.pdf. 

[^kaku]: Kaku, Sonia. "Navigating the Digital Landscape: Understanding and Managing Your Digital Footprint." *Global Media Journal*, July 23, 2024. https://www.globalmediajournal.com/open-access/navigating-the-digital-landscape-understanding-and-managing-your-digital-footprint.pdf. 
